# Default values for vote.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
image: 
  repository: gcr.io/codefresh-sa/example-voting-app/vote
  tag: latest

redis:
  usePassword: false

replicaCount: 1
