apiVersion: v1
description: Helm Chart for Docker example-voting-app
name: example-voting-app
keywords:
- codefresh
- kubernetes
- example-voting-app
version: 2.0.0
sources:
- https://github.com/salesdemocf/example-voting-app
maintainers:
- name: Dustin Van Buskirk
  email: dustin@codefresh.io